services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: fast_km:build
    ports:
      - "${API_PORT}:8000"                   # HOST_PORT:CONTAINER_PORT
      - "8501:8501"
    volumes:
      - ./_data:/app/_data
      - /tmp:/tmp
    environment:
      - REDIS=redis:6379
      - HIGH=${HIGH}                         # optional, ok if env var is blank or not set
      - MEDIUM=${MEDIUM}                     # optional, ok if env var is blank or not set
      - LOW=${LOW}                           # optional, ok if env var is blank or not set
      - PUBMED_API_KEY=${PUBMED_API_KEY}     # optional, ok if env var is blank or not set
      - OPENAI_API_KEY=${OPENAI_API_KEY}     # optional, ok if env var is blank or not set
      - HTCONDOR_TOKEN=${HTCONDOR_TOKEN}     # optional, ok if env var is blank or not set
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY} # optional, ok if env var is blank or not set
      - TIMEZONE=${TIMEZONE}                 # optional, ok if env var is blank or not set
    depends_on:
      - redis
    networks:
      - fast_km-network

  redis:
    image: redis
    networks:
      - fast_km-network

networks:
  fast_km-network: